Data/EntityComponents.sbc
fix for Issue #71 Not saving ModStorageComponent
=> fix for Issue#71 Not saving ModStorageComponent 

CoreSystems.sln, Data/Scripts/CoreSystems/AudioVisual/RunAv.cs
Effects were not displaying properly because you commented out the wrong line lol
=> Fix Barrel1 effects position

Data/Scripts/CoreSystems/EntityComp/EntityInit.cs
=> Fix inventory bug

CoreSystems.csproj, Data/Scripts/CoreSystems/Api/CoreSystemsApiDefs.cs, Data/Scripts/CoreSystems/Definitions/CoreDefinitions.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
Depth & falloff implemented under GridDamage2.  Primary-only damage flow tidied up slightly, and application of force restored.
Still pending depth>max radius handling for penetrative shots.
Max absorb still pending.
Surely some cleanup opportunities still exist.
=> Depth & Falloff... Depth & Falloff

Data/Scripts/CoreSystems/Definitions/CoreDefinitions.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
I think I deselected DamageGrid2....
=> Radiate & Detonate

Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
root block>1x1x1 uses same logic as 1x1x1s.  Transparency & logs suppressed
=> Hope it doesn't explode and irradiate all of us

Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
Legacy data scrape and pool methods sorted out.  Might work.  probably
=> Third time is a charm!

Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
Repointed to consts for legacy compatibility
=> Shield Dmg fix

Data/Scripts/CoreSystems/Definitions/CoreSystems.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
=> AOE Debug Transparency

Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs
=> Depth fix for rounded values

Data/Scripts/CoreSystems/Projectiles/Projectile.cs
=> Advanced Offset Var fix

Data/Scripts/CoreSystems/Ai/AiConstruct.cs, Data/Scripts/CoreSystems/EntityComp/EntityFields.cs, Data/Scripts/CoreSystems/Projectiles/Projectile.cs, Data/Scripts/CoreSystems/Projectiles/ProjectileTypes.cs, Data/Scripts/CoreSystems/Session/SessionCompMgr.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs, Data/Scripts/CoreSystems/Session/SessionFields.cs, Data/Scripts/CoreSystems/Session/SessionInit.cs, Data/Scripts/CoreSystems/Session/SessionRun.cs, Data/Scripts/CoreSystems/Support/Log.cs
Wep and ammo configs scraped and data output as CSV with headers.  Damage logged by weapon type and grid.
=> All the nerdy info

Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponComp.cs, Data/Scripts/CoreSystems/Projectiles/ProjectileHits.cs, Data/Scripts/CoreSystems/Session/SessionCleanUp.cs, Data/Scripts/CoreSystems/Session/SessionFields.cs, Data/Scripts/CoreSystems/Session/SessionInit.cs, Data/Scripts/CoreSystems/Session/SessionJobs.cs, Data/Scripts/CoreSystems/Support/Api/WaterModAPI.cs
Water api to 18 from 15, fixed references to class name change
Changed submersion checks
(commented out) added splash/bubble effects
=> Water API Update

Data/Scripts/CoreSystems/AudioVisual/RunAv.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponTracking.cs, Data/Scripts/CoreSystems/Projectiles/Projectile.cs, Data/Scripts/CoreSystems/Projectiles/ProjectileHits.cs, Data/Scripts/CoreSystems/Projectiles/ProjectileStart.cs, Data/Scripts/CoreSystems/Projectiles/ProjectileTypes.cs, Data/Scripts/CoreSystems/Projectiles/Projectiles.cs, Data/Scripts/CoreSystems/Session/SessionCompMgr.cs, Data/Scripts/CoreSystems/Session/SessionDamageMgr.cs, Data/Scripts/CoreSystems/Session/SessionJobs.cs, Data/Scripts/CoreSystems/Session/SessionTypes.cs
Give Me Strength  (FOR REVIEW ONLY)
Grav update
DmgLog uninit fix
Depth info fixed (supposedly was an issue at 0 or -1) addressed in aconst and dmg routine
Indirect Fire Mk2
=> Indirect Fire Changes

Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponComp.cs, Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponTracking.cs
Grav lead back to 320
Note update
=> Indirect fire from any angle.

Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponTracking.cs, Data/Scripts/CoreSystems/Session/SessionEvents.cs, Data/Scripts/CoreSystems/Session/SessionFields.cs, Data/Scripts/CoreSystems/Session/SessionJobs.cs
Fixin jank
Update SessionRun.cs
=> Fixin stuff

Data/Scripts/CoreSystems/Ai/AiConstruct.cs, Data/Scripts/CoreSystems/Session/SessionCompMgr.cs, Data/Scripts/CoreSystems/Session/SessionFields.cs, Data/Scripts/CoreSystems/Session/SessionRun.cs, Data/Scripts/CoreSystems/Support/Log.cs
-Player name for grids in griddmgstats
-Count of weapons in dmgstats
=> Log Improvements

Data/Scripts/CoreSystems/Ai/AiTypes.cs, Data/Scripts/CoreSystems/Definitions/CoreSystems.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Projectiles/Projectile.cs, Data/Scripts/CoreSystems/Session/SessionJobs.cs
-Added grav drop note
Improvements
-Smarts/Drones start track based on LOS to target, if one is set
-suspecteddrone true if warhead, PB, cockpit, RC, thruster onboard
-Repel range set to 1km based on typical PD range in the top mod packs
=> Grav Log Note

Data/Scripts/CoreSystems/Ai/AiTargeting.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/AmmoConstants.cs, Data/Scripts/CoreSystems/Definitions/SerializedConfigs/Weapon/ProtoWeapon.cs, Data/Scripts/CoreSystems/EntityComp/Controls/CreateCustomActions.cs, Data/Scripts/CoreSystems/EntityComp/Controls/TerminalHelpers.cs, Data/Scripts/CoreSystems/EntityComp/Controls/Weapon/WeaponActions.cs, Data/Scripts/CoreSystems/EntityComp/Controls/Weapon/WeaponUi.cs, Data/Scripts/CoreSystems/EntityComp/Parts/Weapon/WeaponComp.cs, Data/Scripts/CoreSystems/Session/SessionControls.cs
-Added LG/SG switches for terminal and hotbar
=> Fun Things

Data/Scripts/CoreSystems/Api/ApiBackend.cs
it was squaring ai.MaxTargetingRangeSqr instead of ai.MaxTargetingRange.....
=> Fix GetEntityInfo pbapi method

Data/Scripts/CoreSystems/Api/ApiBackend.cs, Data/Scripts/CoreSystems/Api/CoreSystemsApiBase.cs, Data/Scripts/CoreSystems/Api/CoreSystemsApiBlocks.cs
Add 3 new API methods to Weapon Core:
IsWeaponShooting:
Gets whether the weapon is shooting
GetShotsFired:
Gets how many shots the weapon fired before reload
GetMuzzleInfo:
Get a list that contains every muzzle's Position, LocalPosition, Direction, UpDirection, ParentMatrix, DummyMatrix
=> API Extensions

Data/Scripts/CoreSystems/Session/SessionSupport.cs
Spherical restriction reciprocal checks
=> Box origin change
